### PR TITLE
Yo

### PR DESCRIPTION
**Pull request by valpackett**
Made it faster and right-er :)

### CODE REVIEW

**Comment by valpackett** [comment]
BTW, you can delete last 3 commits

**Comment by kaievns** [comment]
as i remember the builds were a bit smaller without those changes, but okay, let it be.

could you also ditch those comments you've added, people normally know the difference between `==null` and `===null` and why stashing `array.length` into a viable is a good idea. And don't forget to run `nake check`

**Comment by valpackett** [comment]
I used `nake test`. And I'm not sure that people know about stashing `arr.length` in a variable… because most people don't do it.

**Comment by kaievns** [comment]
`nake test` runs the server-side version tests. To run the actual tests you need top open the `test/index.html` file in your browser. `nake check` runs jslint code style checks.

regarding the `most people`, most people shouldn't tinkle with the thing :). besides, too much comments distract people from the actual code.

will merge the things shortly

**Comment by kaievns** [comment]
merged! https://github.com/rightjs/rightjs-core/commits/master

thanks for your help! :)

**Comment by valpackett** [comment]
BTW, I checked the browser tests too

**Pull request merged**
